/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateReviewDto {
  productId: string;
  lineItemId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  body: string;
  title?: string;
  images?: Blob[];
}
