/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ShopifyOrder } from './shopifyOrder';

export interface GetCustomerOrdersResponse {
  items: ShopifyOrder[];
  /** @nullable */
  nextCursor: number | null;
  /** @nullable */
  nextCursorString: string | null;
}
