/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ReviewWithoutUser } from './reviewWithoutUser';

export interface GetMyReviewsResponse {
  items: ReviewWithoutUser[];
  /** @nullable */
  nextCursor: number | null;
}
