/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ReviewableLineItem } from './reviewableLineItem';

export interface GetReviewableItemsResponse {
  targetOrderItems: ReviewableLineItem[];
  otherItems: ReviewableLineItem[];
}
