/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface LoginResponseDto {
  /** Success message */
  message: string;
  /** User ID */
  userId: number;
  /** Whether the user is newly registered */
  isNewUser: boolean;
}
