/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { Review } from './review';

export interface ReviewHelpful {
  id: number;
  reviewId: number;
  review: Review;
  userId: number;
  createdAt: string;
}
