/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { ReviewHelpful } from './reviewHelpful';

export interface Review {
  id: number;
  productId: string;
  lineItemId: string;
  rating: number;
  title?: string;
  body: string;
  images: string[];
  helpfulCount: number;
  userId: number;
  user: User;
  helpfulUsers: ReviewHelpful[];
  createdAt: string;
  updatedAt: string;
}
