/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface Review {
  id: number;
  productId: string;
  rating: number;
  title?: string;
  body: string;
  userId: number;
  user: User;
  createdAt: string;
  updatedAt: string;
}
