/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ShopifyCustomerDefaultAddress } from './shopifyCustomerDefaultAddress';

export interface ShopifyCustomer {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  acceptsMarketing: boolean;
  defaultAddress: ShopifyCustomerDefaultAddress;
}
