/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API Documentation
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { Cart } from './cart';
import type { Review } from './review';
import type { WishlistItem } from './wishlistItem';

export interface User {
  id: number;
  firebaseUid?: string;
  shopifyCustomerId?: string;
  provider: string;
  email: string;
  firstName?: string;
  lastName?: string;
  shopifyAccessToken?: string;
  shopifyAccessTokenExpiresAt?: string;
  cart?: Cart;
  reviews: Review[];
  wishlistItems: WishlistItem[];
  createdAt: string;
  updatedAt: string;
}
